##
# Task file in Ansible role "users" to securely lock deprecated user accounts.
#

---
# file: cleanup.yml

- name: "Grab the user list"
  shell: cat /etc/passwd
  register: passwd

- name: "Unlock legitimate user accounts"
  command: usermod --unlock {{item.split(':').0}}
  when: item.split(':').0 in users
    and item.split(':').2|int > 499
  with_items: passwd.stdout_lines

- name: "Lock deprecated user accounts"
  command: usermod --lock {{item.split(':').0}}
  when: item.split(':').0 not in users
    and item.split(':').2|int > 499
  with_items: passwd.stdout_lines

- name: "Disable ssh keys for deprecated user accounts"
  command: rm {{item.split(':').5}}/.ssh/authorized_keys
  when: item.split(':').0 not in users
    and item.split(':').2|int > 499
  with_items: passwd.stdout_lines
